runtime: nodejs20
instance_class: F1

env_variables:
  NODE_ENV: 'production'
  WEATHER_API_KEY: '63f2bd663a2dffe834fd6d3adee562e7'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

handlers:
  - url: /.*
    script: auto
    secure: always
